development:
  adapter: postgresql
  database: docisin_development
  pool: 5
  host: localhost
  port: 5432
  username: mariafamador
  password: paradi5e

test:
  adapter: postgresql
  database: docisin_test
  pool: 5
  host: localhost
  port: 5432
  username: mariafamador
  password: paradi5e

production:
  adapter: postgresql
  database: docisin_production
  pool: 5
  host: localhost
  port: 5432
  username: mariafamador
  password: paradi5e  
