defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *defaults
  database: docisin_development

test:
  <<: *defaults
  database: docisin_test

staging:
  <<: *defaults
  database: docisin_staging

production:
  <<: *defaults
  database: docisin_production
